### ISSUE TITLE
菜鸟的提问

### ISSUE THREAD

**Issue by Mr-FSM** [liuxx001/bird-front#1]
最近刚上手antd,react页刚看，刚好对这个权限控制很头疼，正好想参照你的，弄到我项目里去

**Comment by Mr-FSM** [comment]
好像antd,更新之后增加了权限控制的相关内容但是我不是很懂怎么用

**Comment by liuxx001** [comment]
你说的是antd pro的权限吧，官方有介绍文档的。
https://pro.ant.design/docs/authority-management-cn
https://pro.ant.design/components/Authorized-cn/

或者看看我的前后端分离模式下的权限方案博客：
http://www.cnblogs.com/liuyh/p/8027833.html

**Comment by Mr-FSM** [comment]
antd怎么实现超级用户给不同用户分配权限

**Comment by liuxx001** [comment]
@Mr-FSM 那就不仅仅是前端的问题了，要结合服务端来做。前端只做用户权限获取、临时存储、权限验证、拦截等。而一个用户究竟有哪些权限，这个应该是登录时服务端返给你的。
