### ISSUE TITLE
你好，项目运行出来我觉得挺好的，可是入口文件是哪个啊？

### ISSUE THREAD

**Issue by JserJser** [liuxx001/bird-front#10]
你好，我对你的项目非常的感兴趣，可是我不知道哪个是入口文件，一开始页面就是在login页面，这个是怎么控制的啊？

**Comment by liuxx001** [comment]
[(https://github.com/liuxx001/bird-front/blob/master/src/models/app.js)](/src/models/app.js)

68~75 行
