### ISSUE TITLE
关于权限问题

### ISSUE THREAD

**Issue by wangxingkang** [liuxx001/bird-front#7]
项目权限控制采用的与作者基本一致 
       基本思路是这样:
              1、首先对菜单、按钮和后端API做关联  角色赋权限做到所见即所得  
              2、登陆后获取用户信息，获取到用户的页面权限以及按钮权限
              3、按照页面权限递归生产左侧菜单，并按照权限判断是否可渲染此页面
              4、使用权限按钮替换antd按钮组件决定按钮是否隐藏 
       问题： 
               在配置这些数据过程中会比较繁琐，工作量比较大，作者可有什么思路

**Comment by liuxx001** [comment]
我目前的做法是对一些通用的操作，比如crud权限进行一键生成。而前端表格，也可以通过只配置一个权限key来自动校验crud的权限。

**Comment by wangxingkang** [comment]
可以説的具体点吗

**Comment by wangxingkang** [comment]
好的 谢谢了   我这边通过配置数据 可以一键把前端权限录入到后端   解决配置繁琐 问题
